---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-prod
  namespace: tenant2-sops-prod
spec:
  interval: 1m
  serviceAccountName: tenant2-flux-sa
  chart:
    spec:
      chart: gitops/charts/sops/v1.0
      sourceRef:
        kind: GitRepository
        name: git-repository-tenant2
  values:
    environmentKey: tenant2-sops-prod
    deploy:
      image: kubeitglobalsvcauxacrwe.azurecr.io/nginxinc/nginx-unprivileged
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
