---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-api
  namespace: tenant2-flux
spec:
  interval: 1m
  serviceAccountName: tenant2-flux-sa
  chart:
    spec:
      chart: gitops/charts/example-api/v0.4.000
      sourceRef:
        kind: GitRepository
        name: git-repository-tenant2
  values:
    environmentKey: tenant2-flux
    platform-service:
      replicaCount: 1
      image:
        repository: nginxinc/nginx-unprivileged
        tag: latest
        pullPolicy: IfNotPresent
        fluxAutomation:
          enabled: true
          # set to generic, pulling from docker hub. Set Azure if image is being pulled from ACR
          provider: generic
          interval: 1m
          filterTags:
            pattern: '^\d+\.\d+\.\d+$'
          policy:
            semver:
              range: '>=1.0.0'
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 128Mi
