{{- if .Values.environments.prod.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-prod
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "flux-bootstrap.labels" . | nindent 4 }}
    environment: prod
spec:
  interval: {{ .Values.environments.prod.syncInterval }}
  url: {{ .Values.git.url }}
  ref:
    branch: {{ .Values.git.branch }}
  {{- if .Values.sshKey.enabled }}
  secretRef:
    name: {{ .Values.git.secretName }}
  {{- end }}
{{- end }}
