---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-staging
  namespace: tenant2-sops-staging
spec:
  interval: 1m
  path: ./gitops/dev/secrets/staging
  prune: true
  serviceAccountName: tenant2-flux-sa
  sourceRef:
    kind: GitRepository
    name: git-repository-tenant2
  decryption:
    provider: sops
