---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant2
  namespace: sops-staging
spec:
  interval: 1m
  ref:
    branch: feature/test
  url: https://github.com/dnv-opensource/kubeit-flux-example.git
