{{- if and .Values.infrastructure.enabled .Values.infrastructure.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.infrastructure.serviceAccount.name }}
  namespace: {{ .Values.infrastructure.namespace }}
  labels:
    {{- include "flux-bootstrap.labels" . | nindent 4 }}
{{- end }}
