---
apiVersion: v2
description: SOPS example
name: sops
version: 0.0.1
dependencies:
  - name: kubeit-deployment-chart
    alias: deploy
    version: ~2.2.2
    repository: https://dnv-gssit.github.io/kubeit-charts
