apiVersion: v1
appVersion: "1.0"
description: Example API
name: exampleapi
version: 0.0.1
dependencies:
  - name: platform-service
    version: 1.4.7
    repository: "https://dnvgl.github.io/service-mesh-chart"

