platform-service:
  app: admin-api
  version: v1

  gateway:
    exposeService: true
    name: istio-system/global-https-internal-default-gateway
  image:
    fluxAutomation:
      enabled: true
      provider: azure
      interval: 1m

