apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tenant
  namespace: sops-prod
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/dnv-internal/kubeit-flux-example.git
