apiVersion: ENC[AES256_GCM,data:x+c=,iv:0N/n0E0+RIdtYq2a7Y4mPbiSlQ903hICXxZxtRs7HUQ=,tag:axC0Y02JQUHqR6HqOSvk4Q==,type:str]
kind: ENC[AES256_GCM,data:6MVJECfz,iv:BzYYTptWAMY3ovMSlSIl4NfHbLFwUlEaBzb2XE55p2A=,tag:GAJ/N9d6vZp5Cn9LD5k9Vg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6iofmqBT/WDLhWZ6jzGlwXw=,iv:kfErUqVakhqc/qmXbeKbht0v2ImfxNHw7Y2epxqIhaU=,tag:kUF2vPw2noQrb9YYMG4BTQ==,type:str]
    namespace: ENC[AES256_GCM,data:XHl2w/0cYFkwdMQLFqf93uw=,iv:VdNMtS9o3N+SvvNKo/rqHDXD3tfyf/HQatDb0Ar8w+k=,tag:iT0tDfWnin7K47SLZc8S5g==,type:str]
type: ENC[AES256_GCM,data:sRySzrQy,iv:3uyoZUmCll0osxbMVioWpNKUTzp1SE1O4/l8OJKJvLY=,tag:gHYyH/a0Nsrr/5e3deoCYw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:U5KYuQF+MQ1tN+9c,iv:MIzKaiVuoaZoQ1neqfIwYJy3nx1raZ5NTOIWOBpTe+c=,tag:dficxTmrUgFLM96hY5df8g==,type:str]
sops:
    azure_kv:
        - vault_url: https://kubeit-dev-kv-sh-we.vault.azure.net
          name: sops-key
          version: 41116685dad74ac791df315eb4dbdd08
          created_at: "2026-02-18T07:52:20Z"
          enc: csQNteWbIjOMcYlvDHL-R1-xR6TiyN6YPCwtRRZ9JJcmNrOevZY81DcvzO8cx-2aSp_xw18OW3UXeU7d0V0wMQSA6b-BlFJGMP8IeKKErO2jcyvpeZSeIU4zfmfMZusbiMdwIPP4jHFPiTvkPQh7uDzWxyiAh7rghnW_VLZxjd8KxJdFOFDcUEVVYwd79-SwnqsqkGluzworLhb7Vk_OUn6zmalM-et5BfoXYZnK99F51gdGu0QuGFUzDKseWnoxeIlU891bdvmZ4E950xMKFTh9QY_MJxYAzVLc7b0bDIITujTNyiq7mjUbaH1pZMnqo-Z5la4uItrdmirsVTDUkA
    lastmodified: "2026-02-18T07:52:23Z"
    mac: ENC[AES256_GCM,data:LiLw7QK8eP0GJcv93lXuw1g3CGnloVSkUDkoZFjmllLUFxGdNEIk/hc6MY/T+iJVk5kQoFNn2pA1HrBIRI8kpbe56zp/zZP8M6rKl22oD92IcLDrzgdbCREclbEfamGdbC9crk6RU7jafnOTTrpQvCCTaHBa8cDg79h3qN+Cyzk=,iv:5RUhIzOpMs/UsuMc0Eybs2S6/2XUwNhw0srNg0Q7GRA=,tag:Etdm9MFsC/gZke0VaNwmqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
