---
apiVersion: ENC[AES256_GCM,data:8K8=,iv:pffDbSlv+z6PctQLnZlz+sZh7Sj6Ah0b707Y+Qt4JzU=,tag:peeJLJGBr2H5o1EiLbLtww==,type:str]
kind: ENC[AES256_GCM,data:DO+kGj/t,iv:L+Qu7mDY+y0gaQxY9nbphfhejwuJOE0H/FKE8P3Bp24=,tag:PoON/TlKFRUjZbBwJRuEKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qolsf+J2L3XBKxy7gS5mGm4=,iv:K0XI50749tQ647ymtGo5PIR4/x6gKOq/0YyA2ry5zxo=,tag:BG0KmTE6jTwFNz7pgWE16g==,type:str]
    namespace: ENC[AES256_GCM,data:Na+8uv1AOFicrXyP6SGkxc8kF8g=,iv:p7OkcT9J8CFqMRlhC9As+NGosbYjfKUguYujFTgdkvM=,tag:f/Uw4k38U/umtRtvEPAjVA==,type:str]
type: ENC[AES256_GCM,data:4vdp+NMc,iv:aHTAiHZ8vP15rzwsvcHEK0AkK6wgFzxUcWIZLNJb6p8=,tag:OCvXG7qj2i4KNcQ608z27A==,type:str]
stringData:
    password: ENC[AES256_GCM,data:Z6QYztYbMHPjRLjetSdGUQ==,iv:g1YwXx6Fz4Fh6RrxlWyqhJZOcbAOra4Y0tIim1+h5G4=,tag:OYYcvgK87S2ZYzimp2eKnA==,type:str]
sops:
    azure_kv:
        - vault_url: https://kubeit-dev-kv-sh-we.vault.azure.net
          name: sops-key
          version: 41116685dad74ac791df315eb4dbdd08
          created_at: "2026-02-18T07:56:23Z"
          enc: HGC1aS7Eo2_o-JmFycSdzEjUnPXHHVe1WCi5leLphYU2UuGXFj-PIfE8QZLWKX3Nbz17YvRegk66Px1wqsijVXubtj60AnQYT9ZTPaVSkr7VvywjkAvaWa0ZETTSB-ni0eDTv8_qZED-HaiR82FJAaF-kg53NQU2Tg0SDXGJIXAdTO-vK-reaYDmkDe4pc5VThJyA8w4AwixQgJZhuKWmi8d7w8N30ueGO6MOvix1sgAnol8q5M8cpJK-Z34CuOWCs08F52zx8HYV7IKhjBdfKaMmU0Yye6E4HrFi6aF-KGILQ3FPc9p8NVN1FmE1xT51gBCd4eMWYI2GDAR_sqaJg
    lastmodified: "2026-02-18T07:56:29Z"
    mac: ENC[AES256_GCM,data:6aXAtOaJo5EIzfxp+WklJoh9ePhOTMpGjL9U8P8r62LcNZO92F6OeMUdxJPIPwJCvlnAVgnakCDYSQ5wUmYLGxhNJVd65o8/OXWHzDDO/5nI8Tt612dNXsTDx+LOu+Nj7XkBH0J55LsCUaWG1EOZ8L4AbTBFPKW7wNCIJ1ZIwtM=,iv:2GAY2m5eKZzZWp5/Bg3GlSKROmSoxwBzhU88uake30A=,tag:qrbjenXFMEjiKJvb3JzGUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
